version: "3.7"

services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_USERNAME=docker
      - MONGODB_PASSWORD=mongodb
      - MONGODB_DATABASE=linkapi

    volumes:
      - mongodb_data:/bitnami/mongodb
  app:
    build: .
    restart: always
    container_name: linkapi
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - mongodb
    depends_on:
      - mongodb
  
volumes:
  mongodb_data:
    driver: local